import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ChevronRight, RefreshCw, Search, X } from 'lucide-react';
import { toast } from 'react-toastify';
import OwnerLayout from '@/components/layout/OwnerLayout';
import ReceptionistLayout from '@/components/layout/ReceptionistLayout';

const stored = key => localStorage.getItem(key) || sessionStorage.getItem(key);
const labels = { BLOCKED:'Chưa đến lượt', WAITING:'Đang chờ', CALLED:'Đã gọi', IN_PROGRESS:'Đang thực hiện', WAITING_FOR_TEST:'Chờ xét nghiệm', TEST_DONE:'Cần quay lại bác sĩ', PENDING:'Đang chờ', DONE:'Đã hoàn thành', COMPLETED:'Đã hoàn thành', UNASSIGNED:'Chưa phân luồng', CANCELLED:'Đã hủy', SKIPPED:'Đã bỏ qua' };
const active = new Set(['WAITING','CALLED','IN_PROGRESS','WAITING_FOR_TEST','TEST_DONE','PENDING']);

export default function PatientJourneyPage() {
    const isManager = stored('systemRole') === 'CLINIC_MANAGER';
    const Layout = isManager ? OwnerLayout : ReceptionistLayout;
    const [items,setItems] = useState([]), [loading,setLoading] = useState(true), [search,setSearch] = useState(''), [status,setStatus] = useState(''), [sort,setSort] = useState('newest'), [selected,setSelected] = useState(null);
    const load = async () => { setLoading(true); try { const r=await fetch(`${import.meta.env.VITE_API_URL}/api/v1/patient-journeys`,{headers:{Authorization:`Bearer ${stored('token')}`}}); const b=await r.json(); if(!r.ok) throw new Error(b.message||'Không thể tải hành trình bệnh nhân'); setItems(b.data??b); } catch(e){toast.error(e.message)} finally{setLoading(false)} };
    useEffect(()=>{load()},[]);
    const shown=useMemo(()=>items.filter(x=>(!search||`${x.patientName} ${x.phone||''} ${x.visitCode}`.toLowerCase().includes(search.toLowerCase()))&&(!status||x.currentStatus===status)).sort((a,b)=>sort==='waiting'?b.waitingMinutes-a.waitingMinutes:sort==='name'?(a.patientName||'').localeCompare(b.patientName||'','vi'):new Date(b.checkInTime)-new Date(a.checkInTime)),[items,search,status,sort]);
    return <Layout><div className="w-full p-6 lg:p-8 overflow-y-auto space-y-5">
        <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold text-gray-900">Điều phối bệnh nhân</h1><p className="text-sm text-gray-500 mt-1">Theo dõi vị trí hiện tại và bước tiếp theo của cả khách có tài khoản và khách vãng lai.</p></div><button onClick={load} className="h-10 px-4 border rounded-xl flex items-center gap-2 text-sm"><RefreshCw size={16}/>Làm mới</button></div>
        <div className="bg-white border rounded-xl p-4 grid grid-cols-1 md:grid-cols-[1fr_210px_210px] gap-3"><label className="relative"><Search size={16} className="absolute left-3 top-3 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tên, số điện thoại hoặc mã lượt khám" className="w-full h-10 border rounded-lg pl-9 pr-3 text-sm"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="h-10 border rounded-lg px-3 text-sm"><option value="">Tất cả trạng thái</option>{['WAITING','CALLED','IN_PROGRESS','WAITING_FOR_TEST','TEST_DONE','PENDING','COMPLETED','UNASSIGNED'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} className="h-10 border rounded-lg px-3 text-sm"><option value="newest">Check-in mới nhất</option><option value="waiting">Chờ lâu nhất</option><option value="name">Tên A–Z</option></select></div>
        <div className="bg-white border rounded-xl overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead className="bg-gray-50 text-gray-500"><tr>{['Bệnh nhân','Bước hiện tại','Vị trí','Trạng thái','Đã chờ','Bước tiếp theo',''].map(x=><th key={x} className="text-left font-medium px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{shown.map(x=><tr key={x.visitId} className={x.warning?'bg-amber-50/40':''}><td className="px-4 py-4"><p className="font-semibold">{x.patientName||'-'}</p><p className="text-xs text-gray-500">{x.guest?'Khách vãng lai':'Có tài khoản'} · {x.phone||'-'} · {x.visitCode}</p></td><td className="px-4">{x.currentStep}</td><td className="px-4">{x.currentRoom}</td><td className="px-4"><span className="inline-flex items-center gap-1 px-2 py-1 rounded-lg bg-blue-50 text-blue-700 text-xs">{x.warning&&<AlertTriangle size={13}/>} {labels[x.currentStatus]||x.currentStatus}</span></td><td className="px-4">{x.waitingMinutes} phút</td><td className="px-4">{x.nextStep}</td><td className="px-4"><button onClick={()=>setSelected(x)} className="p-2 hover:bg-gray-100 rounded-lg"><ChevronRight size={17}/></button></td></tr>)}</tbody></table>{!loading&&!shown.length&&<p className="p-12 text-center text-gray-400">Không có bệnh nhân phù hợp.</p>}{loading&&<p className="p-12 text-center text-gray-400">Đang tải...</p>}</div>
        {selected&&<div className="fixed inset-0 bg-black/40 z-50 flex justify-end"><div className="bg-white h-full w-full max-w-xl p-6 overflow-y-auto"><div className="flex justify-between mb-6"><div><h2 className="text-xl font-bold">{selected.patientName}</h2><p className="text-sm text-gray-500">{selected.visitCode} · {selected.guest?'Khách vãng lai':'Có tài khoản'}</p></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="space-y-0">{selected.steps.map((step,i)=><div key={step.id} className="flex gap-4"><div className="flex flex-col items-center"><span className={`w-4 h-4 rounded-full border-2 ${active.has(step.status)?'bg-blue-500 border-blue-500':step.status==='BLOCKED'?'bg-white border-gray-300':'bg-green-500 border-green-500'}`}/>{i<selected.steps.length-1&&<span className="w-px h-20 bg-gray-200"/>}</div><div className="pb-8"><p className="font-semibold">{step.serviceName}</p><p className="text-sm text-gray-500">{step.roomName} ({step.roomCode||'-'})</p><p className="text-xs mt-1 text-blue-600">{labels[step.status]||step.status}</p></div></div>)}</div></div></div>}
    </div></Layout>;
}
