import { useEffect, useState } from 'react';
import { Check, X } from 'lucide-react';
import { toast } from 'react-toastify';
import OwnerLayout from '@/components/layout/OwnerLayout';
const get=k=>localStorage.getItem(k)||sessionStorage.getItem(k); const auth=()=>({Authorization:`Bearer ${get('token')}`});
const vi={MORNING:'Ca sáng',AFTERNOON:'Ca chiều',EVENING:'Ca tối',ON_TIME:'Đúng giờ',LATE:'Đi muộn',WORKING:'Đang làm việc',COMPLETED:'Đã hoàn thành',LEFT_EARLY:'Về sớm',ABSENT:'Vắng mặt',ADJUSTMENT_PENDING:'Chờ điều chỉnh',NOT_CHECKED_IN:'Chưa check-in'};
const fmt=v=>v?new Date(v).toLocaleString('vi-VN'):'—';
export default function AttendanceManagementPage(){
 const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [rows,setRows]=useState([]);const [pending,setPending]=useState([]);const [reviewTarget,setReviewTarget]=useState(null);const [reviewNote,setReviewNote]=useState('');
 const load=async()=>{const [a,b]=await Promise.all([fetch(`${import.meta.env.VITE_API_URL}/api/v1/attendance/manage?date=${date}`,{headers:auth()}),fetch(`${import.meta.env.VITE_API_URL}/api/v1/attendance/adjustments/pending`,{headers:auth()})]);const da=await a.json(),db=await b.json();if(a.ok)setRows(da);else toast.error(da.message||'Không thể tải chấm công.');if(b.ok)setPending(db);};
 useEffect(()=>{load();},[date]);
 const review=async()=>{if(!reviewTarget)return;if(!reviewTarget.approved&&!reviewNote.trim())return toast.error('Vui lòng nhập lý do từ chối.');const r=await fetch(`${import.meta.env.VITE_API_URL}/api/v1/attendance/adjustments/${reviewTarget.id}/review`,{method:'PUT',headers:{...auth(),'Content-Type':'application/json'},body:JSON.stringify({approved:reviewTarget.approved,note:reviewNote.trim()})});const d=await r.json();if(!r.ok)return toast.error(d.message||'Không thể xử lý đề nghị.');toast.success(reviewTarget.approved?'Đã duyệt điều chỉnh.':'Đã từ chối đề nghị.');setReviewTarget(null);setReviewNote('');load();};
 return <OwnerLayout><div className="p-6 md:p-8 space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">Quản lý chấm công</h1><p className="mt-1 text-sm text-gray-500">Theo dõi theo lịch làm việc và duyệt đề nghị điều chỉnh</p></div><label className="text-sm">Ngày<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="ml-2 rounded-lg border px-3 py-2"/></label></div>
 {pending.length>0&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold">Đề nghị đang chờ duyệt ({pending.length})</h2><div className="mt-3 grid gap-3 lg:grid-cols-2">{pending.map(x=><div key={x.id} className="rounded-xl bg-white p-4 border"><b>{x.staffName}</b><p className="mt-1 text-sm text-gray-600">{x.reason}</p><p className="mt-2 text-xs text-gray-500">Check-in: {fmt(x.requestedCheckIn)} • Check-out: {fmt(x.requestedCheckOut)}</p><div className="mt-3 flex gap-2"><button onClick={()=>setReviewTarget({id:x.id,approved:true})} className="flex items-center gap-1 rounded-lg bg-green-600 px-3 py-2 text-sm text-white"><Check size={15}/>Duyệt</button><button onClick={()=>setReviewTarget({id:x.id,approved:false})} className="flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><X size={15}/>Từ chối</button></div></div>)}</div></section>}
 <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-gray-500"><tr><th className="p-4">Nhân viên</th><th className="p-4">Ca</th><th className="p-4">Check-in</th><th className="p-4">Check-out</th><th className="p-4">Trạng thái</th></tr></thead><tbody>{rows.map(x=><tr key={x.scheduleId} className="border-t"><td className="p-4"><b>{x.staffName}</b><p className="text-xs text-gray-400">{x.staffCode}</p></td><td className="p-4">{vi[x.shift]||x.shift}</td><td className="p-4">{fmt(x.checkInAt)}</td><td className="p-4">{fmt(x.checkOutAt)}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">{vi[x.status]||x.status}</span></td></tr>)}</tbody></table>{!rows.length&&<p className="p-10 text-center text-gray-500">Không có lịch làm việc trong ngày này.</p>}</div>
 {reviewTarget&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-lg font-semibold">{reviewTarget.approved?'Duyệt điều chỉnh':'Từ chối điều chỉnh'}</h2><textarea value={reviewNote} onChange={e=>setReviewNote(e.target.value)} placeholder={reviewTarget.approved?'Ghi chú (không bắt buộc)':'Nhập lý do từ chối'} className="mt-4 min-h-28 w-full rounded-xl border p-3 text-sm"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>{setReviewTarget(null);setReviewNote('')}} className="rounded-lg border px-4 py-2">Hủy</button><button onClick={review} className="rounded-lg bg-gray-900 px-4 py-2 text-white">Xác nhận</button></div></div></div>}
 </div></OwnerLayout>;
}
