export const ROUTES = {
    HOME: '/profile',
    LOGIN: '/login',
    REGISTER: '/register',
    APPOINTMENT: '/appointment',
    WAITING_ROOM: '/customer/waiting-room',
    EXAMINATION: '/doctor/examination/:visitId',
    RECEPTION: '/receptionist',
    PROFILE: '/customer/profile',
    MY_APPOINTMENTS: '/my-appointments',
    MEDICAL_RECORD:  '/medical-record',
    SETTINGS:        '/settings',
    CUSTOMER_HOME: '/customer',
    CUSTOMER_VISIT_HISTORY: '/customer/visits',
    CUSTOMER_TEST_RESULTS: '/customer/tests',
    CUSTOMER_PAYMENT: '/customer/payments',

    RECEPTIONIST_APPOINTMENT_DETAIL: '/receptionist/appointments/:id',
    RECEPTIONIST_CHECKIN:       '/receptionist/check-in',
    RECEPTIONIST_CREATE_TICKET: '/receptionist/create-ticket',
    RECEPTIONIST_RECORDS:       '/receptionist/records',
    RECEPTIONIST_SETTINGS:      '/receptionist/settings',
    RECEPTIONIST_SUPPORT:       '/receptionist/support',
};