export const ROUTES = {
    HOME: '/profile',
    LOGIN: '/login',
    REGISTER: '/register',
    APPOINTMENT: '/appointment',
    GUEST_JOURNEY: '/guest/journey',
    CUSTOMER_APPOINTMENT: '/customer/appointment',
    CUSTOMER_FAMILY_MEMBERS: '/customer/family-members',
    CUSTOMER_MEMBERSHIP_CARD: '/customer/membership-card',
    WAITING_ROOM: '/customer/waiting-room',
    EXAMINATION: '/doctor/examination/:visitId',
    RECEPTION: '/receptionist',
    PROFILE: '/customer/profile',
    MY_APPOINTMENTS: '/my-appointments',
    MEDICAL_RECORD:  '/medical-record',
    SETTINGS:        '/settings',
    CUSTOMER_HOME: '/customer',
    CUSTOMER_VISIT_HISTORY: '/customer/visits',
    CUSTOMER_MEDICAL_RECORD_PRINT: '/customer/medical-records/:recordId/print',
    CUSTOMER_TEST_RESULTS: '/customer/tests',
    CUSTOMER_PAYMENT: '/customer/payments',
    CUSTOMER_APPOINTMENT_DETAIL: '/my-appointments/:id',
    RECEPTIONIST_APPOINTMENT_DETAIL: '/receptionist/appointments/:id',
    RECEPTIONIST_CHECKIN:       '/receptionist/check-in',
    RECEPTIONIST_CREATE_TICKET: '/receptionist/create-ticket',
    RECEPTIONIST_VISITS:        '/receptionist/visits',
    RECEPTIONIST_RECORDS:       '/receptionist/records',
    RECEPTIONIST_PATIENT_DETAIL: '/receptionist/patients/:id',
    RECEPTIONIST_PATIENT_VISIT_DETAIL: '/receptionist/patients/:id/visits/:visitId',
    RECEPTIONIST_SETTINGS:      '/receptionist/settings',
    RECEPTIONIST_SUPPORT:      '/receptionist/support',
    RECEPTIONIST_FOLLOW_UPS:   '/receptionist/follow-ups',
    RECEPTIONIST_FEEDBACKS:    '/receptionist/feedbacks',
    PATIENT_JOURNEYS: '/staff/patient-journeys',


    CASHIER_INVOICES: '/cashier/invoices',
    CASHIER_MEMBERSHIP_TOPUP: '/cashier/membership-top-up',
    CASHIER_MEMBERSHIP_TOPUP_HISTORY: '/cashier/membership-top-up/history',
    CASHIER_PRINTER:  '/cashier/printer',
    CASHIER_HELP:     '/cashier/help',
    CASHIER_INVOICE_DETAIL: '/cashier/invoices/:id',
    CASHIER_INVOICE_PRINT: '/cashier/invoices/:id/print',
    PATIENT_VISIT_HISTORY: '/patient/visits',
    PATIENT_VISIT_DETAIL:  '/patient/visits',

    DOCTOR_ROOMS: '/doctor/rooms',
    DOCTOR_DEPARTMENTS: '/doctor/departments/:departmentId',
    DOCTOR_PATIENTS:    '/doctor/patients',
    DOCTOR_RECORDS:     '/doctor/records',
    DOCTOR_EXAMINATION: '/doctor/examinations/department/:departmentId',
    DOCTOR_PRESCRIPTION_PREVIEW: '/doctor/prescriptions/:recordId/preview',
    DOCTOR_EXAM_COMPLETED: '/doctor/examinations/:recordId/completed',
    DOCTOR_MEDICAL_RECORD_PRINT: '/doctor/medical-records/:recordId/print',
    DOCTOR_LAB: '/doctor/lab/:departmentId',
    DOCTOR_LAB_CALL: '/doctor/lab/:departmentId/call',
    QUEUE_DISPLAY_LAUNCHER: '/staff/queue-displays',
    ROOM_QUEUE_DISPLAY: '/display/room/:departmentId',
    ALL_QUEUE_DISPLAY: '/display/queues',

    DOCTOR_LAB_DETAIL: '/lab/:id',

    ADMIN_ACCOUNTS: '/admin/accounts',
    ADMIN_ROOMS:    '/admin/rooms',
    ADMIN_SERVICES: '/admin/services',
    ADMIN_CAPABILITIES: '/admin/capabilities',
    ADMIN_AUDIT_LOGS: '/admin/audit-logs',
    ADMIN_SHIFTS: '/admin/shifts',
    ADMIN_SCHEDULE: '/admin/schedule',
    ADMIN_PUBLIC_ANNOUNCEMENTS: '/admin/public-announcements',
    ADMIN_CLINIC_INFORMATION: '/admin/clinic-information',
    ADMIN_MEMBERSHIP_POLICY: '/admin/membership-policy',
    CLINICAL_FORM_TEMPLATES: '/manager/clinical-form-templates',

    OWNER_SCHEDULE: '/owner/schedule',
    OWNER_REPORT: '/owner/report',
    OWNER_FEEDBACKS: '/owner/feedbacks',
    MANAGER_STAFF: '/manager/staff',
    MANAGER_PATIENTS: '/manager/patients',

    STAFF_SCHEDULE: '/staff/schedule',
    STAFF_PROFILE: '/staff/profile',
    RECEPTIONIST_RECORD_DETAIL: '/receptionist/records/:id',
};
